<?php
class db_cache_store{
 public static $_YM_YWCA = array(id => 30 , name => 'YM-YWCA', default_tag_id => '7');
 public static $_XS_CARGO = array(id => 33 , name => 'XS CARGO', default_tag_id => '11');
 public static $_Winners = array(id => 49 , name => 'Winners', default_tag_id => '19');
 public static $_Walmart = array(id => 42 , name => 'Walmart', default_tag_id => '15');
 public static $_VINCI_PARK = array(id => 21 , name => 'VINCI PARK', default_tag_id => '5');
 public static $_Value_Village = array(id => 41 , name => 'Value Village', default_tag_id => '23');
 public static $_US_Airways = array(id => 70 , name => 'US Airways', default_tag_id => '18');
 public static $_UNIFUND = array(id => 24 , name => 'UNIFUND', default_tag_id => '6');
 public static $_Uber = array(id => 103 , name => 'Uber', default_tag_id => '14');
 public static $_TOYS_R_US = array(id => 15 , name => 'TOYS R US', default_tag_id => '19');
 public static $_TOOTSIES_Shoe_Market = array(id => 101 , name => 'TOOTSIES Shoe Market', default_tag_id => '19');
 public static $_Tim_Hortons = array(id => 59 , name => 'Tim Hortons', default_tag_id => '17');
 public static $_TIKI_MING = array(id => 12 , name => 'TIKI MING', default_tag_id => '17');
 public static $_THE_WORKS = array(id => 99 , name => 'THE WORKS', default_tag_id => '17');
 public static $_The_Ottawa_Hospital = array(id => 104 , name => 'The Ottawa Hospital', default_tag_id => '24');
 public static $_The_Farm_Team = array(id => 62 , name => 'The Farm Team', default_tag_id => '17');
 public static $_Thai_Express = array(id => 8 , name => 'Thai Express', default_tag_id => '17');
 public static $_Taxi = array(id => 69 , name => 'Taxi', default_tag_id => '14');
 public static $_TARGET = array(id => 77 , name => 'TARGET', default_tag_id => '19');
 public static $_Talay_Thai = array(id => 88 , name => 'Talay Thai', default_tag_id => '17');
 public static $_Subway = array(id => 35 , name => 'Subway', default_tag_id => '17');
 public static $_Starbucks = array(id => 60 , name => 'Starbucks', default_tag_id => '17');
 public static $_Staples = array(id => 32 , name => 'Staples', default_tag_id => '11');
 public static $_Sports_Experts = array(id => 13 , name => 'Sports Experts', default_tag_id => '19');
 public static $_SportChek = array(id => 52 , name => 'SportChek', default_tag_id => '19');
 public static $_Sofa_World = array(id => 40 , name => 'Sofa World', default_tag_id => '23');
 public static $_Shoppers = array(id => 34 , name => 'Shoppers', default_tag_id => '10');
 public static $_SHELL = array(id => 22 , name => 'SHELL', default_tag_id => '20');
 public static $_ServiceOntario = array(id => 95 , name => 'ServiceOntario', default_tag_id => '7');
 public static $_Second_Cup = array(id => 16 , name => 'Second Cup', default_tag_id => '17');
 public static $_SEARS = array(id => 18 , name => 'SEARS', default_tag_id => '19');
 public static $_Scotiabank = array(id => 23 , name => 'Scotiabank', default_tag_id => '4');
 public static $_SALEM_STORE = array(id => 84 , name => 'SALEM STORE', default_tag_id => '7');
 public static $_Rogers_Wireless = array(id => 39 , name => 'Rogers Wireless', default_tag_id => '16');
 public static $_Rockwell_s_Restaurant = array(id => 92 , name => 'Rockwell s Restaurant', default_tag_id => '17');
 public static $_ROAM_Mobility = array(id => 75 , name => 'ROAM Mobility', default_tag_id => '16');
 public static $_RED_PEPPER_THAI = array(id => 11 , name => 'RED PEPPER THAI', default_tag_id => '17');
 public static $_Presto = array(id => 87 , name => 'Presto', default_tag_id => '14');
 public static $_PIONEER = array(id => 19 , name => 'PIONEER', default_tag_id => '20');
 public static $_Petro_Canada = array(id => 94 , name => 'Petro-Canada', default_tag_id => '20');
 public static $_Paypal = array(id => 80 , name => 'Paypal', default_tag_id => '2');
 public static $_other = array(id => 3 , name => 'other', default_tag_id => '2');
 public static $_ON_THE_RUN = array(id => 25 , name => 'ON THE RUN', default_tag_id => '17');
 public static $_Old_Navy = array(id => 37 , name => 'Old Navy', default_tag_id => '19');
 public static $_OC_Transpo = array(id => 46 , name => 'OC Transpo', default_tag_id => '14');
 public static $_none = array(id => 1 , name => 'none', default_tag_id => '1');
 public static $_NANAS_SOUL_FOOD = array(id => 74 , name => 'NANAS SOUL FOOD', default_tag_id => '17');
 public static $_N_A = array(id => 2 , name => 'N/A', default_tag_id => '3');
 public static $_Montanas = array(id => 66 , name => 'Montanas', default_tag_id => '17');
 public static $_MID_EAST = array(id => 4 , name => 'MID EAST', default_tag_id => '15');
 public static $_MICHAEL_HILL = array(id => 98 , name => 'MICHAEL HILL', default_tag_id => '19');
 public static $_Metro = array(id => 55 , name => 'Metro', default_tag_id => '15');
 public static $_McDonalds = array(id => 90 , name => 'McDonalds', default_tag_id => '17');
 public static $_Malones_Lakeside = array(id => 10 , name => 'Malones Lakeside', default_tag_id => '17');
 public static $_MAGICJACK = array(id => 65 , name => 'MAGICJACK', default_tag_id => '2');
 public static $_MAGENTA_STUDIO = array(id => 82 , name => 'MAGENTA STUDIO', default_tag_id => '7');
 public static $_Loblaw = array(id => 58 , name => 'Loblaw', default_tag_id => '15');
 public static $_Leon_s = array(id => 100 , name => 'Leon s', default_tag_id => '23');
 public static $_Jysk = array(id => 76 , name => 'Jysk', default_tag_id => '23');
 public static $_JOE_FRESH = array(id => 17 , name => 'JOE FRESH', default_tag_id => '19');
 public static $_JOCKS___JILLS = array(id => 73 , name => 'JOCKS & JILLS', default_tag_id => '17');
 public static $_JERSEY_MIKES_SUBS = array(id => 72 , name => 'JERSEY MIKES SUBS', default_tag_id => '17');
 public static $_JAMES_STREET_PUB = array(id => 91 , name => 'JAMES STREET PUB', default_tag_id => '17');
 public static $_Independant = array(id => 56 , name => 'Independant', default_tag_id => '15');
 public static $_Ikea = array(id => 47 , name => 'Ikea', default_tag_id => '23');
 public static $_HYDRO_OTTAWA = array(id => 28 , name => 'HYDRO OTTAWA', default_tag_id => '9');
 public static $_Hyatt = array(id => 67 , name => 'Hyatt', default_tag_id => '18');
 public static $_HomeSense = array(id => 57 , name => 'HomeSense', default_tag_id => '23');
 public static $_Home_Hardware = array(id => 50 , name => 'Home Hardware', default_tag_id => '22');
 public static $_Home_Depot = array(id => 51 , name => 'Home Depot', default_tag_id => '22');
 public static $_Hilton = array(id => 68 , name => 'Hilton', default_tag_id => '18');
 public static $_Harveys = array(id => 38 , name => 'Harveys', default_tag_id => '17');
 public static $_HAKIM_OPTICAL = array(id => 78 , name => 'HAKIM OPTICAL', default_tag_id => '24');
 public static $_GRAND_PIZZERIA = array(id => 86 , name => 'GRAND PIZZERIA', default_tag_id => '17');
 public static $_Google = array(id => 96 , name => 'Google', default_tag_id => '19');
 public static $_GoDaddy = array(id => 102 , name => 'GoDaddy', default_tag_id => '2');
 public static $_Giant_Tiger = array(id => 20 , name => 'Giant Tiger', default_tag_id => '19');
 public static $_Gas_Station = array(id => 54 , name => 'Gas Station', default_tag_id => '20');
 public static $_Food_Basics = array(id => 45 , name => 'Food Basics', default_tag_id => '15');
 public static $_Expedia = array(id => 89 , name => 'Expedia', default_tag_id => '18');
 public static $_ESSO = array(id => 53 , name => 'ESSO', default_tag_id => '20');
 public static $_ENBRIDGE = array(id => 29 , name => 'ENBRIDGE', default_tag_id => '8');
 public static $_EINSTEINS_BROS_BAGEL = array(id => 71 , name => 'EINSTEINS BROS BAGEL', default_tag_id => '17');
 public static $_EB_GAMES = array(id => 83 , name => 'EB GAMES', default_tag_id => '25');
 public static $_DUFRESNE = array(id => 85 , name => 'DUFRESNE', default_tag_id => '23');
 public static $_Dollarama = array(id => 36 , name => 'Dollarama', default_tag_id => '11');
 public static $_Dollar_Tree = array(id => 31 , name => 'Dollar Tree', default_tag_id => '11');
 public static $_DIXON_MNGT = array(id => 27 , name => 'DIXON MNGT', default_tag_id => '11');
 public static $_Damas = array(id => 61 , name => 'Damas', default_tag_id => '15');
 public static $_Costco = array(id => 43 , name => 'Costco', default_tag_id => '15');
 public static $_CORA_Breakfast = array(id => 93 , name => 'CORA Breakfast', default_tag_id => '17');
 public static $_Canadian_Tire = array(id => 48 , name => 'Canadian Tire', default_tag_id => '11');
 public static $_Bulk_Barn = array(id => 97 , name => 'Bulk Barn', default_tag_id => '15');
 public static $_Blue_Line = array(id => 63 , name => 'Blue Line', default_tag_id => '14');
 public static $_BIG_RIG = array(id => 6 , name => 'BIG RIG', default_tag_id => '17');
 public static $_BestBuy = array(id => 44 , name => 'BestBuy', default_tag_id => '13');
 public static $_BED_BATH___BEYOND = array(id => 64 , name => 'BED BATH & BEYOND', default_tag_id => '23');
 public static $_BEAVERTAILS = array(id => 81 , name => 'BEAVERTAILS', default_tag_id => '17');
 public static $_BANK_OF_MONTREAL = array(id => 26 , name => 'BANK OF MONTREAL', default_tag_id => '21');
 public static $_ARZ_LEBANESE = array(id => 7 , name => 'ARZ LEBANESE', default_tag_id => '17');
 public static $_Amazon = array(id => 79 , name => 'Amazon', default_tag_id => '19');
 public static $_ALDO = array(id => 14 , name => 'ALDO', default_tag_id => '19');
 public static $_A_W = array(id => 9 , name => 'A&W', default_tag_id => '17');
 public static $_168_Sushi = array(id => 5 , name => '168 Sushi', default_tag_id => '17');
}
class db_cache_tag{
 public static $_Travel = array(id => 18 , name => 'Travel');
 public static $_Transportation = array(id => 14 , name => 'Transportation');
 public static $_Shopping = array(id => 19 , name => 'Shopping');
 public static $_Phone_and_Internet = array(id => 16 , name => 'Phone and Internet');
 public static $_Pharmacy = array(id => 10 , name => 'Pharmacy');
 public static $_Personal = array(id => 7 , name => 'Personal');
 public static $_Parking = array(id => 5 , name => 'Parking');
 public static $_other = array(id => 2 , name => 'other');
 public static $_none = array(id => 1 , name => 'none');
 public static $_N_A = array(id => 3 , name => 'N/A');
 public static $_Mortgage = array(id => 12 , name => 'Mortgage');
 public static $_Medical = array(id => 24 , name => 'Medical');
 public static $_Insurance = array(id => 6 , name => 'Insurance');
 public static $_House_maintenance = array(id => 22 , name => 'House maintenance');
 public static $_Home = array(id => 11 , name => 'Home');
 public static $_Heat = array(id => 8 , name => 'Heat');
 public static $_Gas = array(id => 20 , name => 'Gas');
 public static $_Furniture = array(id => 23 , name => 'Furniture');
 public static $_Food = array(id => 15 , name => 'Food');
 public static $_Entertainment = array(id => 25 , name => 'Entertainment');
 public static $_Electronics = array(id => 13 , name => 'Electronics');
 public static $_Electricity_and_Water = array(id => 9 , name => 'Electricity and Water');
 public static $_Eat_out = array(id => 17 , name => 'Eat out');
 public static $_Car = array(id => 21 , name => 'Car');
 public static $_Banking = array(id => 4 , name => 'Banking');
}
?>